### ISSUE TITLE
MqttChannelHandler.handlePuback()空指针崩溃

### ISSUE THREAD

**Issue by hursing** [jetlinks/netty-mqtt-client#4]
```
private void handlePuback(MqttPubAckMessage message) {
    MqttPendingPublish pendingPublish = this.client.getPendingPublishes().get(message.variableHeader().messageId());
    pendingPublish.getFuture().setSuccess(null);
    pendingPublish.onPubackReceived();
    this.client.getPendingPublishes().remove(message.variableHeader().messageId());
    pendingPublish.getPayload().release();
}
```
pendingPublish可以是空指针。
必现场景：发送一条QoS1的消息后立刻断网，再连接后会崩溃。原因：
MqttClientImpl.publish函数有一段：
```
this.pendingPublishes.put(pendingPublish.getMessageId(), pendingPublish);
pendingPublish.startPublishRetransmissionTimer(this.eventLoop.next(), this::sendAndFlushPacket);
```
这个pendingPublishes变量会在MqttClientImpl.connect()函数里
pendingPublishes.clear();
但是RetransmissionTimer并没有停止，reconnect后仍会发送成功，接着收到Puback。这时pendingPublishes这个Map里已经不存在这个messageId的消息了。

**Comment by zhou-hao** [comment]
这个库已经弃用。建议使用  [netty/codec-mqtt](https://github.com/netty/netty/tree/4.1/codec-mqtt)  或者 [vertx-mqtt](https://github.com/vert-x3/vertx-mqtt)
